services:
  backend:
    build:
      context: ./backend
    container_name: mixi-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: mixi-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend